# Auto-generated by PyGUI Builder Pro
import customtkinter as ctk

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")

root = ctk.CTk()
root.title("My App")
root.geometry("700x500")

# Progressbar
progressbar1 = ctk.CTkProgressBar(root, fg_color="#3498db", corner_radius=10, width=150)
progressbar1.set(0.5)
progressbar1.place(x=100, y=100)

# Frame
frame2 = ctk.CTkFrame(root, fg_color="#f0f0f0", corner_radius=10, width=150, height=35)
frame2.place(x=104, y=165)

# Radiobutton
radiobutton3 = ctk.CTkRadioButton(root, text="Radiobutton 3", font=("Arial", 12), fg_color="#3498db")
radiobutton3.place(x=428, y=89)

# Radiobutton
radiobutton4 = ctk.CTkRadioButton(root, text="Radiobutton 4", font=("Arial", 12), fg_color="#3498db")
radiobutton4.place(x=115, y=233)

root.mainloop()
